version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - /app/data
    environment:
      - PORT=8000
      - DATABASE_PATH=/app/data/financial_data.db
      - JWT_SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - ENGINE_WILCO_AI_URL=${ENGINE_WILCO_AI_URL}

    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
